#!/usr/bin/env bash
# configures a new nginx server on ubuntu, create index.nginx-debian.html, test it
apt-get update
apt-get -y install nginx
mv /usr/share/nginx/html/index.nginx-debian.html /usr/share/nginx/html/index.nginx-debian.html.backup
echo "Hello World!" > /usr/share/nginx/html/index.nginx-debian.html
service nginx restart
