#!/usr/bin/env bash
# configures a new nginx server on ubuntu with a redirect
apt-get -y update
apt-get -y install nginx
sed -i '46 i \\trewrite ^/redirect_me http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
